"""Agregar tabla reportes_guardados

Revision ID: 0065ebeb6263
Revises: 06374a022094
Create Date: 2026-05-15 18:17:21.322074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0065ebeb6263'
down_revision = '06374a022094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_plantillas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_plantillas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('tipo_reporte', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filtros', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('columnas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reportes_plantillas_pkey'))
    )
    # ### end Alembic commands ###
