"""Agregar columna rol_id a usuarios

Revision ID: 06374a022094
Revises: 59edaf49ab79
Create Date: 2026-05-12 13:30:58.338348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06374a022094'
down_revision = '59edaf49ab79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notificaciones_email', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notificaciones_whatsapp', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notificaciones_whatsapp')
        batch_op.drop_column('notificaciones_email')
        batch_op.drop_column('rol_id')

    # ### end Alembic commands ###
