"""agregar campo google_id a usuario

Revision ID: 59edaf49ab79
Revises: 7b7643617354
Create Date: 2026-05-10 16:36:55.299467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59edaf49ab79'
down_revision = '7b7643617354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
