"""Actualizar modelo notificaciones

Revision ID: 7b7643617354
Revises: 89b00acf9454
Create Date: 2026-04-25 21:44:13.254897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7643617354'
down_revision = '89b00acf9454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificaciones_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_leido'), ['leido'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificaciones_usuario_email'), ['usuario_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificaciones_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_leido'))
        batch_op.drop_index(batch_op.f('ix_notificaciones_fecha_creacion'))

    # ### end Alembic commands ###
