"""Agregar respuesta_a a mensajes

Revision ID: 89b00acf9454
Revises: a6d1e71ed925
Create Date: 2026-04-25 21:43:15.795208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b00acf9454'
down_revision = 'a6d1e71ed925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_tramite_folio'), ['tramite_folio'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_tramite_tipo'), ['tramite_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_usuario_email'), ['usuario_email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_mensajes_tramite_tipo'))
        batch_op.drop_index(batch_op.f('ix_mensajes_tramite_folio'))

    # ### end Alembic commands ###
