"""Agregar columna respuesta_a a mensajes

Revision ID: a6d1e71ed925
Revises: 07c7a5734732
Create Date: 2026-04-25 21:08:35.655376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d1e71ed925'
down_revision = '07c7a5734732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respuesta_a', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'mensajes', ['respuesta_a'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('respuesta_a')

    # ### end Alembic commands ###
