"""agregar verificacion email

Revision ID: cf8244829c57
Revises: 2867b7107c36
Create Date: 2026-05-24 21:00:34.738061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8244829c57'
down_revision = '2867b7107c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_verificacion', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('token_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('token_expiracion')
        batch_op.drop_column('token_verificacion')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
