"""Agregar reportes_guardados

Revision ID: d12f86971105
Revises: 0065ebeb6263
Create Date: 2026-05-15 18:28:03.867794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12f86971105'
down_revision = '0065ebeb6263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_guardados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estilos_json', sa.Text(), nullable=True))

    with op.batch_alter_table('reportes_plantillas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estilos_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_plantillas', schema=None) as batch_op:
        batch_op.drop_column('estilos_json')

    with op.batch_alter_table('reportes_guardados', schema=None) as batch_op:
        batch_op.drop_column('estilos_json')

    # ### end Alembic commands ###
